[package]
name = "Skyrim: Home Of The Nords"
version = "25.05"
description = "100+ quests, including new regional questlines for the Imperial Guilds, bounty hunting, and miscellaneous quests; 290+ exterior cells of hand-crafted landscape; 330+ interior cells, including the massive cities of Karthwasten and Dragonstar, towns, camps, and dozens of locations for you to loot in classic TES fashion. "
homepage = "https://www.nexusmods.com/morrowind/mods/44921"

[dependencies.mods."Tamriel_Data"]
version = ">=12"
url = "https://www.nexusmods.com/morrowind/mods/44537"